Fix warnings for Rust 1.85.1 in packages/modules/Uwb
```
FAILED: out/soong/.intermediates/packages/modules/Uwb/libuwb-uci/src/libuwb_core_tests/android_riscv64/libuwb_core_tests64.clippy
ANDROID_RUST_VERSION=1.85.1 out/host/linux-x86/bin/rustc_wrapper prebuilts/rust/linux-x86/1.85.1/bin/clippy-driver --emit metadata -o out/soong/.intermediates/packages/modules/Uwb/libuwb-uci/src/libuwb_core_tests/android_riscv64/libuwb_core_tests64.clippy --emit dep-info=out/soong/.intermediates/packages/modules/Uwb/libuwb-uci/src/libuwb_core_tests/android_riscv64/libuwb_core_tests64.clippy.d.raw packages/modules/Uwb/libuwb-uci/src/rust/uwb_core/src/lib.rs --extern bytes=out/soong/.intermediates/external/rust/android-crates-io/crates/bytes/libbytes/android_riscv64_rlib_rlib-std/libbytes.rlib --extern num_traits=out/soong/.intermediates/external/rust/android-crates-io/crates/num-traits/libnum_traits/android_riscv64_rlib_rlib-std/libnum_traits.rlib --extern log=out/soong/.intermediates/external/rust/android-crates-io/crates/log/liblog_rust/android_riscv64_rlib_rlib-std/liblog_rust.rlib --extern pdl_runtime=out/soong/.intermediates/external/rust/android-crates-io/crates/pdl-runtime/libpdl_runtime/android_riscv64_rlib_rlib-std/libpdl_runtime.rlib --extern thiserror=out/soong/.intermediates/external/rust/android-crates-io/crates/thiserror/libthiserror/android_riscv64_rlib_rlib-std/libthiserror.rlib --extern tokio=out/soong/.intermediates/external/rust/android-crates-io/crates/tokio/libtokio/android_riscv64_rlib_rlib-std/libtokio.rlib --extern uwb_uci_packets=out/soong/.intermediates/packages/modules/Uwb/libuwb-uci/src/libuwb_uci_packets/android_riscv64_rlib_rlib-std/libuwb_uci_packets.rlib --extern zeroize=out/soong/.intermediates/external/rust/android-crates-io/crates/zeroize/libzeroize/android_riscv64_rlib_rlib-std/libzeroize.rlib --extern env_logger=out/soong/.intermediates/external/rust/android-crates-io/crates/env_logger/libenv_logger/android_riscv64_rlib_rlib-std/libenv_logger.rlib --extern tempfile=out/soong/.intermediates/external/rust/android-crates-io/crates/tempfile/libtempfile/android_riscv64_rlib_rlib-std/libtempfile.rlib --extern test=out/soong/.intermediates/prebuilts/rust/libtest/android_riscv64_rlib_rlib-std/libtest.rlib --extern std=out/soong/.intermediates/prebuilts/rust/libstd/android_riscv64_rlib/libstd.rlib --extern async_trait=out/soong/.intermediates/external/rust/android-crates-io/crates/async-trait/libasync_trait/linux_glibc_x86_64/libasync_trait.so --extern num_derive=out/soong/.intermediates/external/rust/android-crates-io/crates/num-derive/libnum_derive/linux_glibc_x86_64/libnum_derive.so -L out/soong/.intermediates/external/rust/android-crates-io/crates/serde/libserde/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/prebuilts/rust/libstd/android_riscv64_rlib/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/serde_derive/libserde_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/prebuilts/rust/libcompiler_builtins.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libcore.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/librustc_demangle.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/liblibc.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libcfg_if.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/liballoc.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libhashbrown.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libunwind.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libprofiler_builtins.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libstd_detect.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/prebuilts/rust/libpanic_abort.rust_sysroot/android_riscv64_rlib/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/android_log-sys/libandroid_log_sys/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/once_cell/libonce_cell/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/system/logging/liblog/liblog/android_riscv64_shared/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/bytes/libbytes/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/thiserror/libthiserror/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/thiserror-impl/libthiserror_impl/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/libc/liblibc/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/mio/libmio/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/pin-project-lite/libpin_project_lite/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/socket2/libsocket2/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/tokio-macros/libtokio_macros/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/rustversion/librustversion/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/log/liblog_rust/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/num-traits/libnum_traits/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/pdl-runtime/libpdl_runtime/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/zeroize/libzeroize/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/num-derive/libnum_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/zeroize_derive/libzeroize_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/cfg-if/libcfg_if/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/fastrand/libfastrand/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/rustix/librustix/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/bitflags/libbitflags/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/errno/liberrno/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/prebuilts/rust/liblibc.rust_toolchain/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/prebuilts/rust/libcfg_if.rust_toolchain/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/prebuilts/rust/libgetopts/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/prebuilts/rust/libunicode_width.rust_toolchain/android_riscv64_rlib_rlib-std/ -L out/soong/.intermediates/bionic/libc/libc/android_riscv64_shared_current/ -L out/soong/.intermediates/bionic/libm/libm/android_riscv64_shared_current/ -L out/soong/.intermediates/bionic/libdl/libdl/android_riscv64_shared_current/ -L prebuilts/clang/host/linux-x86/clang-r547379/lib/clang/20/lib/linux/ -Z unstable-options -Z stack-protector=strong -Z remap-cwd-prefix=. -C debuginfo=2 -C opt-level=3 -C overflow-checks=on -C force-unwind-tables=yes -C symbol-mangling-version=v0 --color=always -Z dylib-lto -Z link-native-libraries=no -Z force-unstable-if-unmarked --cfg soong -C force-frame-pointers=y  -C panic=abort -Z debug-info-for-profiling -Z tls-model=global-dynamic -C relocation-model=pic -C lto=thin -A deprecated -A unknown_lints -D missing-docs -D warnings -D unsafe_op_in_unsafe_fn --edition=2021 --test -A missing-docs -Z panic_abort_tests --crate-type=bin --target=riscv64-linux-android --sysroot=/dev/null -C codegen-units=1 -Zallow-features="" -A clippy::disallowed_names -A clippy::empty_line_after_doc_comments -A clippy::type-complexity -A clippy::unnecessary_fallible_conversions -A clippy::unnecessary-wraps -A clippy::unusual-byte-groupings -A clippy::upper-case-acronyms -D clippy::undocumented_unsafe_blocks
error: operator precedence can trip the unwary
    --> packages/modules/Uwb/libuwb-uci/src/rust/uwb_core/src/uci/uci_manager.rs:1977:39
     |
1977 |         let mut bytes: Vec<u8> = vec![(mt & 0x7) << 5 | (pbf & 0x1) << 4 | (gid & 0xF), oid & 0x3F];
     |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `((mt & 0x7) << 5) | ((pbf & 0x1) << 4)`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence
     = note: `-D clippy::precedence` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(clippy::precedence)]`

error: aborting due to 1 previous error
```

Bug: 421269002
Test: m rust
Flag: EXEMPT refactor
Change-Id: Ieaa4a877799ce0b8dab7d210151d353a3bddd120